routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| This file is where you may define all of the routes that are handled
| by your application. Just tell Laravel the URIs it should respond
| to using a Closure or controller method. Build something great!
|
*/

Route::get('/load', function () {
    return redirect('/');
});

Auth::routes();

Route::get('/home', 'HomeController@index');

Route::get('/coupon', 'AgentController@coupon');
Route::get('/custom', 'AgentController@custom');
Route::get('/agent', 'AgentController@index');//index
Route::get('/', 'AgentController@load');
Route::get('/commission', 'AgentController@commission');
Route::get('/reg', 'AgentController@reg');
Route::post('/saveAgentInfo', 'AgentController@saveAgentInfo');

Route::get('/rule', 'AgentController@rule');
Route::get('/share', 'AgentController@share');


Route::group(['prefix' => 'admin'], function () {

    Route::get('/','UserController@userList');
    Route::get('/userEdit/{user}','UserController@userEdit');
    Route::post('/userUpdate','UserController@userUpdate');

});


Route::get('/wechatcheck','WechatController@validateWechatToken');
Route::any('/wechatLoginCallback','WechatController@wechatLoginCallback');


Route::resource('client','ClientController');
Route::get('/myClients', 'ClientController@myClients');//对应register view
Route::get('/clientAdd', 'ClientController@clientAdd');//对应register view
Route::post('/clientInfoSave', 'ClientController@clientInfoSave');//对应register view


Route::resource('progress','ProgressController',['except'=>['show','edit']]);
Route::resource('property','PropertyController',['except'=>['show','update']]);
Route::get('property/uploadImage/{property}','PropertyController@uploadImage');
Route::post('property/storeImage','ImageController@storeImage');


Route::resource('image','ImageController',['except'=>['show','update','create','store','destroy']]);


Route::get('configuration/editEstateType','ConfigurationController@editEstateType');
Route::get('configuration/editSaleStage','ConfigurationController@editSaleStage');
Route::get('configuration/editActivityRule','ConfigurationController@editActivityRule');
Route::get('configuration/editSaleStage','ConfigurationController@editSaleStage');
Route::get('configuration/editAgentCareer','ConfigurationController@editAgentCareer');
Route::post('configuration/update/{configuration}','ConfigurationController@update');

app/AgentType.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class AgentType extends Model
{
    //
}

app/Http/Controllers/AgentController.php
<?php

namespace App\Http\Controllers;

use App\User;
use Illuminate\Http\Request;

use App\Http\Requests;
use Illuminate\Support\Facades\Auth;
use App\Configuration;
use App\Property;

class AgentController extends Controller
{
    public function __construct()
    {
        $this->middleware('auth')->except('load');
    }

    public function load()
    {
        //微信第三方登陆地址
        $url = 'https://open.weixin.qq.com/connect/oauth2/authorize?appid=wxa585c7f09efe3ec0&redirect_uri=http://wx.ejwchina.com/wechatLoginCallback&response_type=code&scope=snsapi_userinfo&state=STATE#wechat_redirect';
        return view('agent.load',compact('url'));
    }

    public function coupon()
    {
        return view('agent.coupon');
    }

    public function custom()
    {
        return view('agent.custom');
    }
    public function index()
    {
        $user = Auth::user();
        $properties = Property::where('id','>',1)->get();
        $commission = $user->clients()->with('property')->where('is_finished','>',0)->get()->sum('property.commission');

        //领取微信优惠劵地址
        $shareURL = 'http://mp.weixin.qq.com/bizmall/cardshelf?shelf_id=1&showwxpaytitle=1&biz=MzIzNDQ4NzQyMw==&t=cardticket/shelf_list&scene=1000007#wechat_redirect';
        return view('agent.index',compact('user','properties','shareURL','commission'));
    }

    public function commission()
    {
        $commission = Auth::user()->clients()->with('property')->where('is_finished','>',0)->get()->sum('property.commission');
        $paid_commission = Auth::user()->paid_commission;
        return view('agent.commission',compact('commission','paid_commission'));
    }

    public function reg()
    {
        $conf = Configuration::whereKey('agent_type')->first();
        $agent_types = explode(',',$conf->value);
        return view('agent.reg',compact('agent_types'));
    }


    public function rule()
    {
        $conf = Configuration::where('key','activity_rule')->first();
        return view('agent.rule',compact('conf'));
    }

    public function share()
    {
        $properties = Property::all();
        return view('agent.share',compact('properties'));
    }


    public function saveAgentInfo(Request $request)
    {

        $this->validate($request, [
            'agent_type' => 'required',
            'name'=>'required|max:40',
            'gender' => 'required',
            'phone' => 'required|digits:11',
            'identity_id' => 'required|string|size:18',
        ]);
        $user = Auth::user();
        $data = $request->all();
        $user->update($data);

        return response()->json($user->toArray(),200);
//        return response()->json($request->all(),200);
    }



}

resources/views/agent/commission.blade.php
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="format-detection" content="telephone=no" />
    <meta name="format-detection" content="email=no" />
    <meta name="apple-mobile-web-app-capable" content="yes" />
    <meta name="apple-mobile-web-app-status-bar-style" content="black" />
    <title>全民经纪人</title>

    <link rel="stylesheet" href="static/css/index.css" />
</head>
<body>
<section class="pirce">
    <div class="pirce-top">
        <p>
            <em><img src="static/img/index-icon-2.png" alt=""></em>
            <span>我的佣金</span>
        </p>
    </div>
    <div class="pirce-tab">
        <div class="pirce-tab-con">
            <em class="em-1">{{$commission}}</em>
            <p>应结佣金</p>
        </div>
        <div class="pirce-tab-con">
            <em>{{$paid_commission}}</em>
            <p>已结佣金</p>
        </div>
    </div>
    <!-- <div class="price-btn">
        <p class="sub">绑定银行卡</p>
        <p>没有佣金信息</p>
    </div> -->
</section>

<script src="static/js/jquery-2.1.3.min.js"></script>
<script src="static/js/flexible.js"></script>
</body>
</html>

resources/views/agent/coupon.blade.php
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="format-detection" content="telephone=no" />
    <meta name="format-detection" content="email=no" />
    <meta name="apple-mobile-web-app-capable" content="yes" />
    <meta name="apple-mobile-web-app-status-bar-style" content="black" />
    <title>全民经纪人</title>

    <link rel="stylesheet" href="static/css/index.css" />
</head>
<body>
<section class="coupon">
    <div class="coupon-top">
        <p>
            <span>优惠劵</span>
        </p>
    </div>
    <div class="coupon-con">
        <ul>
            <li class="coupon-li-1">
                <span>黄石公园</span>
            </li>
            <li class="coupon-li-2">
                <img src="static/img/erweima.png" alt="">
            </li>
        </ul>
    </div>
</section>

<script src="static/js/jquery-2.1.3.min.js"></script>
<script src="static/js/flexible.js"></script>
</body>
</html>

resources/views/agent/index.blade.php
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <!-- <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=0" /> -->
    <meta name="format-detection" content="telephone=no" />
    <meta name="format-detection" content="email=no" />
    <meta name="apple-mobile-web-app-capable" content="yes" />
    <meta name="apple-mobile-web-app-status-bar-style" content="black" />
    <title>全民经纪人</title>

    <link rel="stylesheet" href="static/css/index.css" />
</head>
<body>
<section class="index">
    <div class="index-top">
        <div class="index-pic">
            <img src="{{$user->wechat_avatar}}" alt="">
        </div>
        <div class="index-top-text">
            <p>{{$user->name}}</p>
            <p><em>￥{{$commission}}</em>&nbsp;已推荐{{$user->clients()->count()}}人</p>
        </div>
        <div class="index-top-a">
            <a href="{{route('client.create')}}">
                <img src="static/img/tuijiankehu.png" alt="">
            </a>
            <a href="{{$shareURL}}">
                <img src="static/img/share-juan.png" alt="">
            </a>
        </div>
    </div>
    <div class="index-tab">
        <p>
            <a href="{{url('myClients')}}"><img src="static/img/index-icon-1.png" alt="">我的客户</a>
        </p>
        <p>
            <a href="{{url('commission')}}"><img src="static/img/index-icon-2.png" alt="">我的佣金</a>
        </p>
        <p>
            <a href="rule"><img src="static/img/index-icon-3.png" alt="">活动细则</a>
        </p>
    </div>
    <div class="index-con">
        <ul>
            @foreach($properties as $property)
                <li>
                    <div class='index-con-img'>
                        <img src="{{config('app.QNURL').$property->coverage_img}}" alt="">
                    </div>
                    <div class="index-con-p">
                        <div class="index-con-p-title">{{$property->title}}</div>
                        <p class="index-con-p-price">价格：{{$property->price}}</p>
                        <p>佣金：{{$property->commission}}元</p>
                        <p>区域：{{$property->city_area}}</p>
                    </div>
                </li>
            @endforeach
        </ul>
    </div>
</section>
<!-- <script src="js/rem.js"></script> -->

<script src="static/js/jquery-2.1.3.min.js"></script>
<script src="static/js/flexible.js"></script>
</body>
</html>

resources/views/agent/load.blade.php
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="utf-8">
    <meta name="format-detection" content="telephone=no" />
    <meta name="format-detection" content="email=no" />
    <meta name="apple-mobile-web-app-capable" content="yes" />
    <meta name="apple-mobile-web-app-status-bar-style" content="black" />
    <title>全民经纪人</title>

    <link rel="stylesheet" href="static/css/swiper-3.3.1.min.css" />
    <link rel="stylesheet" href="static/css/animate.min.css" />
    <link rel="stylesheet" href="static/css/index.css" />
</head>

<body class="load-bg">
<section class="load">
    <div class="swiper-container">
        <div class="swiper-wrapper">
            <div class="swiper-slide">
                <div class="load-logo_index ani" swiper-animate-effect="fadeInDown" swiper-animate-duration="0.5s" swiper-animate-delay="0s">
                    <img src="static/img/logo.png" alt="">
                </div>
                <div class="load-bb ani" swiper-animate-effect="fadeInDown" swiper-animate-duration="0.5s" swiper-animate-delay="0s">
                    <img src="static/img/index-bb.png" alt="">
                </div>
                <div class="load-dd ani" swiper-animate-effect="fadeInDown" swiper-animate-duration="0.5s" swiper-animate-delay="0s">
                    <img src="static/img/load-ll.png" alt="">
                </div>
                <div class="load-cc ani" swiper-animate-effect="tada" swiper-animate-duration="0.8s" swiper-animate-delay="0.3s">
                    <img src="static/img/load-cc.png" alt="">
                </div>
                <div class="load-reg ani" swiper-animate-effect="bounceInUp" swiper-animate-duration="0.8s" swiper-animate-delay="0.6s">
                    <a href="{{$url}}"><img src="static/img/reg.png" alt=""></a>
                </div>
                <div class="load-reg ani" swiper-animate-effect="bounceInUp" swiper-animate-duration="0.8s" swiper-animate-delay="0.6s">
                    <a href="{{$url}}"><img src="static/img/load-dl.png" alt=""></a>
                </div>
            </div>
        </div>
    </div>
</section>

<script src="/static/js/jquery-2.1.3.min.js"></script>
<script src="/static/js/flexible.js"></script>
<script charset="utf-8" src="/static/js/swiper-3.3.1.min.js"></script>
<script charset="utf-8" src="/static/js/swiper.animate1.0.2.min.js"></script>
<script>
    $(document).ready(function() {
        var mySwiper = new Swiper('.swiper-container', {
            onInit: function(swiper) { //Swiper2.x的初始化是onFirstInit
                swiperAnimateCache(swiper); //隐藏动画元素
                swiperAnimate(swiper); //初始化完成开始动画
            },
            onSlideChangeEnd: function(swiper) {
                swiperAnimate(swiper); //每个slide切换结束时也运行当前slide动画
            }
        })
    })
</script>
</body>

</html>

resources/views/agent/reg.blade.php
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="format-detection" content="telephone=no" />
    <meta name="format-detection" content="email=no" />
    <meta name="apple-mobile-web-app-capable" content="yes" />
    <meta name="apple-mobile-web-app-status-bar-style" content="black" />
    <title>全民经纪人</title>

    <link rel="stylesheet" href="static/css/index1.css" />
</head>
<body>
<section class="reg">
    @include('errors._messages')
    <div class="reg-top">
        <p>
            <em><img src="static/img/index-icon-1.png" alt=""></em>
            <span>注册经纪人</span>
        </p>
    </div>
    <div class="reg-tab">
        <p>以下资料务必真是填写</p>
        <em class="reg-diver"></em>
    </div>
    <div class="reg-form">
        <ul>
            <li>
                <select id="type">
                    @foreach($agent_types as $type)
                    <option value="{{$type}}">{{$type}}</option>
                    @endforeach
                </select>
            </li>
            <li>
                <span>公司名称</span>
                <input type="text" id="company">
            </li>
            <li>
                <span>姓名</span>
                <input type="text" id="name">
            </li>
            <li>
                <select id="gender">
                        <option value="男">男</option>
                        <option value="女">女</option>
                </select>
            </li>
            <li>
                <span>手机号</span>
                <input type="text" id="phone" type="number" max="19999999999" min="10000000000">
            </li>
            <li>
                <span>身份证</span>
                <input type="text" id="indentity">
            </li>
            <li class="checkbox">
                <p>
                    <em></em>我已阅读合作协议并同意
                </p>
            </li>
            <li class="sub">
                <p id="submitForm">注册</p>
            </li>
        </ul>
    </div>
</section>

<script src="static/js/jquery-2.1.3.min.js"></script>
<script src="static/js/flexible.js"></script>

<script>


    $("#submitForm").click(function(){
        var para = {
            agent_type : $('#type').val(),
            company : $('#company').val(),
            name : $('#name').val(),
            gender : $('#gender').val(),
            phone : $('#phone').val(),
            identity_id : $('#indentity').val(),
            _token : "{{ csrf_token() }}"
        }


        $.ajax({
            url: "{{url('saveAgentInfo')}}",
            type: "post",
            dataType: "json",
            data: para,
            success: function (data) {
                window.location.href='{{url('agent')}}'; // 跳转到B目录
            },
            error: function (data) {
                alert('填写数据不合法,或者电话号码已经注册,请重新填写')

            }
        });
    });
</script>

</body>
</html>

resources/views/agent/rule.blade.php
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="format-detection" content="telephone=no" />
    <meta name="format-detection" content="email=no" />
    <meta name="apple-mobile-web-app-capable" content="yes" />
    <meta name="apple-mobile-web-app-status-bar-style" content="black" />
    <title>全民经纪人</title>

    <link rel="stylesheet" href="static/css/index.css" />
</head>
<body>
<section class="rule">
    <div class="rule-top">
        <p>
            <span>活动规则</span>
        </p>
    </div>
    <div class="rule-ul">
        {{--<ul>--}}
            {{--<li>--}}
                {{--<p>黄石公园</p>--}}
                {{--<p>洋房-8000元/套</p>--}}
                {{--<p>高层-5000元/套</p>--}}
            {{--</li>--}}
            {{--<li>--}}
                {{--<p>联润商贸城</p>--}}
                {{--<p>商铺-8000元/套</p>--}}
                {{--<p>高层-5000元/套</p>--}}
            {{--</li>--}}
        {{--</ul>--}}

        {!! $conf->value !!}

    </div>
    {{--<div class="rule-con">--}}
        {{--<p>推介及奖金领取流程：</p>--}}
        {{--<p>1、推介的客户为营销中心从未接待和登记过的来访客户。</p>--}}
        {{--<p>2、介绍客户签约成功并全款到位。</p>--}}
        {{--<p>3、客户签约成功并全款到位后30日内发放全额奖金。（税金自理）--}}
            {{--活动截止时间：2016年12月31日</p>--}}
        {{--<p>e家经济人有权在法律允许的范围内保留对本次活动的最终解释权。</p>--}}
    {{--</div>--}}
    {{--<div class="rule-btn">--}}
        {{--<a href="javascript:history.go(-1)"><p class="sub">返回首页</p></a>--}}
    {{--</div>--}}
</section>

<script src="static/js/jquery-2.1.3.min.js"></script>
<script src="static/js/flexible.js"></script>
</body>
</html>

resources/views/agent/share.blade.php
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="utf-8">
        <meta name="format-detection" content="telephone=no" />
        <meta name="format-detection" content="email=no" />
        <meta name="apple-mobile-web-app-capable" content="yes" />
        <meta name="apple-mobile-web-app-status-bar-style" content="black" />
        <title>全民经纪人</title>

        <link rel="stylesheet" href="static/css/index.css" />
    </head>
    <body>
        <section class="share">
            <div class="share-top">
                <p>
                    <em><img src="static/img/share-pic.png" alt=""></em>
                    <span>分享优惠劵</span>
                </p>
            </div>
            <div class="share-form">
                <ul>
                    <li>
                        <select name="property">
                            @foreach($properties as $property)
                            <option value="{{$property->title}}">{{$property->title}}</option>
                            @endforeach
                        </select>
                    </li>
                    <li class="textarea">
                        <textarea name="discount_info" placeholder="您的朋友可以享受的分享优惠"></textarea>
                    </li>
                    <li class="sub">
                        <p>生成优惠劵</p>
                    </li>
                </ul>
            </div>
        </section>

        <script src="static/js/jquery-2.1.3.min.js"></script>
        <script src="static/js/flexible.js"></script>
        <script type="text/javascript">
            $(function(){
                $('.sub p').on('click',function(){
                    window.location.href="{{url('coupon')}}";
                });
            });
        </script>
    </body>
</html>