routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| This file is where you may define all of the routes that are handled
| by your application. Just tell Laravel the URIs it should respond
| to using a Closure or controller method. Build something great!
|
*/

Route::get('/load', function () {
    return redirect('/');
});

Auth::routes();

Route::get('/home', 'HomeController@index');

Route::get('/coupon', 'AgentController@coupon');
Route::get('/custom', 'AgentController@custom');
Route::get('/agent', 'AgentController@index');//index
Route::get('/', 'AgentController@load');
Route::get('/commission', 'AgentController@commission');
Route::get('/reg', 'AgentController@reg');
Route::post('/saveAgentInfo', 'AgentController@saveAgentInfo');

Route::get('/rule', 'AgentController@rule');
Route::get('/share', 'AgentController@share');


Route::group(['prefix' => 'admin'], function () {

    Route::get('/','UserController@userList');
    Route::get('/userEdit/{user}','UserController@userEdit');
    Route::post('/userUpdate','UserController@userUpdate');

});


Route::get('/wechatcheck','WechatController@validateWechatToken');
Route::any('/wechatLoginCallback','WechatController@wechatLoginCallback');


Route::resource('client','ClientController');
Route::get('/myClients', 'ClientController@myClients');//对应register view
Route::get('/clientAdd', 'ClientController@clientAdd');//对应register view
Route::post('/clientInfoSave', 'ClientController@clientInfoSave');//对应register view


Route::resource('progress','ProgressController',['except'=>['show','edit']]);
Route::resource('property','PropertyController',['except'=>['show','update']]);
Route::get('property/uploadImage/{property}','PropertyController@uploadImage');
Route::post('property/storeImage','ImageController@storeImage');


Route::resource('image','ImageController',['except'=>['show','update','create','store','destroy']]);


Route::get('configuration/editEstateType','ConfigurationController@editEstateType');
Route::get('configuration/editSaleStage','ConfigurationController@editSaleStage');
Route::get('configuration/editActivityRule','ConfigurationController@editActivityRule');
Route::get('configuration/editSaleStage','ConfigurationController@editSaleStage');
Route::get('configuration/editAgentCareer','ConfigurationController@editAgentCareer');
Route::post('configuration/update/{configuration}','ConfigurationController@update');

app/Property.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Property extends Model
{
    protected $fillable = [
        'title','detail',
        'coverage_img',
        'images','city_area',
        'address',
        'feature','price',
        'commission',
        'commission_title',
        'commission_detail'
    ];

    public function coupons () {
        return $this->hasMany('App\Coupon');
    }

    public function getCoverageUrlAttribute() {
        return config('app.QNURL').$this->coverage_img;
    }



    public function getCoverageH100Attribute() {
        $para = '?imageView2/2/h/200/interlace/1/q/100|watermark/2/text/ReWutue7j-e6quS6ug==/font/5a6L5L2T/fontsize/50/fill/I0RGMTYxNg==/dissolve/100/gravity/North/dy/10
';
        return config('app.QNURL').$this->coverage_img.$para;
    }

    public function clients() {
        return $this->hasMany('App\Client');
    }
}

app/Http/Controllers/PropertyController.php
<?php

namespace App\Http\Controllers;

use App\Progress;
use Illuminate\Http\Request;

use App\Http\Requests;
use App\Property;
use Illuminate\Support\Facades\Session;

use Illuminate\Support\Facades\Storage;

use Illuminate\Support\Facades\File;

class PropertyController extends Controller
{
    //

    public function __construct()
    {
        $this->middleware('auth');
    }

    public function index() {
        $properties = Property::all();
        return view('property.index',compact('properties'));
    }

    public function create() {
        return view('property.create');
    }

    public function edit(Property $property) {
        //dd(config('app.QNURL'));
        return view('property.edit',compact('property'));
    }

    public function store(Request $request) {
        $id = $request->input('id');
        if($id) {//编辑

            try {
                //commission
                $p = Property::find($id);
                $p->update($request->all());
                $p->save();
            } catch(\Exception $e) {
                Session::flash('error', $e->getMessage());
            }
        } else {//增加

            try {
                Property::create($request->all());
            } catch(\Exception $e) {
                Session::flash('error', $e->getMessage());
            }
        }
        return redirect(route('property.index'));
    }




    public function destroy (Property $property) {
        $res = $property->delete();

        return redirect(action('PropertyController@index'));
    }



    public function uploadImage(Property $property) {
        return view('property.uploadImage',compact('property'));
    }





}

resources/views/property/create.blade.php
@extends('layouts.admin')


@section('meta_title','添加楼盘信息')


@section('content')
    <h2 class="text-center">添加楼盘信息</h2>
    <div class="well-lg">
        {!! Form::open(['route' => 'property.store', 'method' => 'post']) !!}

        {!! Form::label('title', '楼盘名称(必填)', ['class' => 'control-label text-danger','placeholder'=>'万科城花']) !!}
        {!! Form::text('title', null, ['class' => 'form-control']) !!}

        {!! Form::label('detail', '楼盘详情', ['class' => 'control-label']) !!}
        {!! Form::textarea('detail', null, ['class' => 'form-control','rows'=>'2']) !!}

        {{--{!! Form::label('coverage_img', '封面图片', ['class' => 'control-label']) !!}--}}
        {{--{!! Form::text('coverage_img', null, ['class' => 'form-control']) !!}--}}

        {{--{!! Form::label('images', '其他图片', ['class' => 'control-label']) !!}--}}
        {{--{!! Form::text('images', null, ['class' => 'form-control']) !!}--}}

        {!! Form::label('city_area', '城市/区域', ['class' => 'control-label text-danger','placeholder'=>'光谷高新 关山']) !!}
        {!! Form::text('city_area', null, ['class' => 'form-control']) !!}

        {!! Form::label('address', '地址', ['class' => 'control-label']) !!}
        {!! Form::text('address', null, ['class' => 'form-control']) !!}

        {!! Form::label('feature', '买点/特色', ['class' => 'control-label']) !!}
        {!! Form::text('feature', null, ['class' => 'form-control']) !!}

        {!! Form::label('price', '单价(必填)', ['class' => 'control-label text-danger']) !!}
        {!! Form::text('price', null, ['class' => 'form-control']) !!}


        {!! Form::label('commission', '金额(必填) 元', ['class' => 'control-label text-danger']) !!}
        {!! Form::number('commission',1, ['class' => 'form-control','min'=>'1','max'=>'10000']) !!}

        {!! Form::label('commission_detail', '佣金详情(必填)文字说明', ['class' => 'control-label text-danger']) !!}
        {!! Form::textarea('commission_detail', null, ['class' => 'form-control','rows'=>'2']) !!}

        {!! Form::submit('Submit', ['class' => 'form-control btn-success']) !!}
        {!! Form::close() !!}
    </div>
@endsection



@section('script')
    <script>
        $(function(){
            $('#property').addClass("active");
        });
    </script>
@endsection

resources/views/property/edit.blade.php
@extends('layouts.admin')


@section('meta_title','编辑楼盘信息')


@section('content')

                <div class="well-sm">


                    {!! Form::open(['route' => 'property.store', 'method' => 'post']) !!}
                    {!! Form::text('id', $property->id, ['class' => 'form-control hidden']) !!}
                    {!! Form::label('title', '楼盘名称', ['class' => 'control-label','placeholder'=>'必填']) !!}
                    {!! Form::text('title', $property->title, ['class' => 'form-control']) !!}

                    {!! Form::label('detail', '楼盘详情', ['class' => 'control-label']) !!}
                    {!! Form::textarea('detail', $property->detail, ['class' => 'form-control','rows'=>'2']) !!}

                    {{--{!! Form::label('coverage_img', '封面图片', ['class' => 'control-label']) !!}--}}
                    {{--{!! Form::text('coverage_img', $property->detail, ['class' => 'form-control']) !!}--}}

                    {{--{!! Form::label('images', '其他图片', ['class' => 'control-label']) !!}--}}
                    {{--{!! Form::text('images', $property->images, ['class' => 'form-control']) !!}--}}

                    {!! Form::label('city_area', '城市/区域', ['class' => 'control-label']) !!}
                    {!! Form::text('city_area', $property->city_area, ['class' => 'form-control']) !!}

                    {!! Form::label('address', '地址', ['class' => 'control-label']) !!}
                    {!! Form::text('address', $property->address, ['class' => 'form-control']) !!}

                    {!! Form::label('feature', '买点/特色.房型', ['class' => 'control-label']) !!}
                    {!! Form::text('feature', $property->feature, ['class' => 'form-control']) !!}

                    {!! Form::label('price', '单价', ['class' => 'control-label']) !!}
                    {!! Form::text('price', $property->price, ['class' => 'form-control']) !!}


                    {!! Form::label('commission', '佣金金额(单位元) 金额', ['class' => 'control-label text-danger']) !!}
                    {!! Form::number('commission', $property->commission, ['class' => 'form-control','placeholder'=>'1000','min'=>'1','max'=>'10000']) !!}

                    {!! Form::label('commission_detail', '佣金文字说明', ['class' => 'control-label']) !!}
                    {!! Form::textarea('commission_detail', $property->commission_detail, ['class' => 'form-control','rows'=>'2']) !!}


                    {!! Form::submit('Submit', ['class' => 'form-control btn-success']) !!}
                    {!! Form::close() !!}
                </div>

                @if($property->coverage_img)
                    <h3 class="text-center lead">楼盘封面照片</h3>
                    <img src="{{$property->coverage_url}}" class="img-responsive" alt="Responsive image">
                    <br>
                @endif





@endsection

@section('script')
    <script>
        $(function(){
            $('#property').addClass("active");
        });

        $('#btnImage').click(function(){

            var para = {
                image:$('#coverage_img').val(),
                propertyId:"{{$property->id}}",
                _token:"{{csrf_token()}}"
            };
            $.ajax({
                url: '{{url('admin/uploadCoverageImageForProperty')}}',
                type: 'POST',
                cache: false,
                data: para,
                processData: false,
                contentType: false
            }).done(function(res) {
            });


        });
    </script>
@endsection

resources/views/property/index.blade.php
@extends('layouts.admin')


@section('meta_title','楼盘列表')


@section('content')
    <div class="well-lg">
        <h2 class="text-center text-success"> 楼盘列表</h2>
        <p class="text-right"><a class="btn btn-success" href="{{route('property.create')}}">添加楼盘信息</a> </p>
        <table class="table table-striped table-hover table-responsive table-condensed table-bordered">
            <thead>
            <tr>
                <th>#</th>
                <th>名称</th>
                <th>详情</th>
                <th>封面图片地址</th>
                <th>多张图片</th>
                <th>城市/区域</th>
                <th>地址</th>
                <th>特色买点</th>
                <th>单价</th>
                <th>佣金</th>
                <th>佣金描述</th>
                <th>操作</th>
            </tr>
            </thead>
            <tbody>
            @foreach($properties as $property)
                <tr>
                    <td>{{$property->id}}</td>
                    <td>{{$property->title}}</td>
                    <td>{{$property->detail}}</td>
                    <td>
                        <img src="{{$property->coverage_h100}}" class="img-responsive" alt="Responsive image">
                    </td>
                    <td>{{$property->images}}</td>
                    <td>{{$property->city_area}}</td>
                    <td>{{$property->address}}</td>
                    <td>{{$property->feature}}</td>
                    <td>{{$property->price}}</td>
                    <td>{{$property->commission}}元</td>
                    <td>{{$property->commission_detail}}</td>
                    <td>
                        <a class="btn btn-primary" href="{{route('property.edit',$property)}}">编辑</a>
                        <a href="{{url('property/uploadImage',$property)}}" class="btn btn-block btn-warning">上传封面</a>

                        {!! Form::model($property, ['route' => ['property.destroy', $property], 'method' => 'delete']) !!}
                        {!! Form::submit('删除', ['class' => 'form-control btn-danger']) !!}
                        {!! Form::close() !!}
                    </td>
                </tr>
            @endforeach

            </tbody>


        </table>

    </div>
@endsection


@section('script')
    <script>
        $(function(){

            $('#property').addClass("active");
        });
    </script>
@endsection

resources/views/property/uploadImage.blade.php
@extends('layouts.admin')


@section('meta_title','上传楼盘图片')


@section('content')

                    <h2 class="text-center text-success"> {{$property->title}}</h2>

                    {!! Form::open(['url' => 'property/storeImage', 'method' => 'post' ,'files'=>true]) !!}

                        {!! Form::label('image', '上传图片', ['class' => 'control-label text-danger']) !!}
                        {!! Form::file('image', ['class' => 'form-control','accept'=>'image/*']) !!}
                        {!! Form::text('property_id',$property->id, ['class' => 'form-control hidden']) !!}
                        {!! Form::submit('上传楼盘封面照片', ['class' => 'form-control btn-success']) !!}
                    {!! Form::close() !!}

@endsection

@section('script')
    <script>
        $(function(){
            $('#property').addClass("active");
        });


    </script>
@endsection