routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| This file is where you may define all of the routes that are handled
| by your application. Just tell Laravel the URIs it should respond
| to using a Closure or controller method. Build something great!
|
*/

Route::get('/load', function () {
    return redirect('/');
});

Auth::routes();

Route::get('/home', 'HomeController@index');

Route::get('/coupon', 'AgentController@coupon');
Route::get('/custom', 'AgentController@custom');
Route::get('/agent', 'AgentController@index');//index
Route::get('/', 'AgentController@load');
Route::get('/commission', 'AgentController@commission');
Route::get('/reg', 'AgentController@reg');
Route::post('/saveAgentInfo', 'AgentController@saveAgentInfo');

Route::get('/rule', 'AgentController@rule');
Route::get('/share', 'AgentController@share');


Route::group(['prefix' => 'admin'], function () {

    Route::get('/','UserController@userList');
    Route::get('/userEdit/{user}','UserController@userEdit');
    Route::post('/userUpdate','UserController@userUpdate');

});


Route::get('/wechatcheck','WechatController@validateWechatToken');
Route::any('/wechatLoginCallback','WechatController@wechatLoginCallback');


Route::resource('client','ClientController');
Route::get('/myClients', 'ClientController@myClients');//对应register view
Route::get('/clientAdd', 'ClientController@clientAdd');//对应register view
Route::post('/clientInfoSave', 'ClientController@clientInfoSave');//对应register view


Route::resource('progress','ProgressController',['except'=>['show','edit']]);
Route::resource('property','PropertyController',['except'=>['show','update']]);
Route::get('property/uploadImage/{property}','PropertyController@uploadImage');
Route::post('property/storeImage','ImageController@storeImage');


Route::resource('image','ImageController',['except'=>['show','update','create','store','destroy']]);


Route::get('configuration/editEstateType','ConfigurationController@editEstateType');
Route::get('configuration/editSaleStage','ConfigurationController@editSaleStage');
Route::get('configuration/editActivityRule','ConfigurationController@editActivityRule');
Route::get('configuration/editSaleStage','ConfigurationController@editSaleStage');
Route::get('configuration/editAgentCareer','ConfigurationController@editAgentCareer');
Route::post('configuration/update/{configuration}','ConfigurationController@update');

app/Client.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Client extends Model
{

    protected $fillable = [
        'user_id','name','phone','gender',
        'property_id','intention_area',
        'intention_price','intention_type','intention_apartment',
        'remark','is_finished','is_recommanding'
    ];

    public function user() {
        return $this->belongsTo('App\User');
    }

    public function progresses () {
        return $this->hasMany('App\Progress');
    }

    public function property() {
        return $this->belongsTo('App\Property');
    }


}

app/Http/Controllers/ClientController.php
<?php

namespace App\Http\Controllers;

use App\Configuration;
use App\Property;
use Illuminate\Http\Request;

use App\Http\Requests;
use Illuminate\Support\Facades\Auth;
use App\Client;


class ClientController extends Controller
{
    public function __construct () {
        $this->middleware('auth');
    }

    public function myClients() {
        $clients = Auth::user()->clients->where('is_finished','=',0);
        $dealers = Auth::user()->clients->where('is_finished','>',0);
        return view('client.myClients',compact('clients','dealers'));
    }


    public function edit(Client $client) {
        return view('client.edit',compact('client'));
    }

    public function index() {
        $clients = Client::all();
        return view('client.index',compact('clients'));
    }

    public function create() {
        $properties = Property::all();
        $propertieTypes = Configuration::whereKey('property_type')->first()->value;
        $propertyTypes = explode(',',$propertieTypes);
        return view('client.create',compact('properties','propertyTypes'));
    }

    public function store (Request $request) {


        $this->validate($request, [
            'name'=>'required|max:40',
            'phone' => 'required|digits:11',
        ]);

        $data = $request->all();
        $data['user_id'] = Auth::user()->id;

        $client = Client::wherePhone($request->input('phone'))->first();
        if ($client) {
            $client->update($data);
        } else {
            Client::create($data);
        }

        return response()->json('添加成功');
    }

    public function update(Request $request,Client $client) {
        $this->validate($request, [
            'name'=>'required|max:40',
            'phone' => 'required|digits:11',
        ]);

        $data = $request->all();
//        dd($data);
        $client->update($data);
        return redirect(route('client.index'));
    }

    public function destroy(Client $client){
        $client->delete();
        return redirect(route('client.index'));
    }

    public function show(Client $client) {
        return view('client.show',compact('client'));
    }



}

resources/views/client/create.blade.php
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="format-detection" content="telephone=no" />
    <meta name="format-detection" content="email=no" />
    <meta name="apple-mobile-web-app-capable" content="yes" />
    <meta name="apple-mobile-web-app-status-bar-style" content="black" />
    <title>全民经纪人</title>

    <link rel="stylesheet" href="/static/css/index1.css" />
</head>
<body>
<section class="register">
    <div class="register-top">
        <p>
            <em><img src="/static/img/register-pic.png" alt=""></em>
            <span>推荐客户</span>
        </p>
    </div>
    <div class="register-tab">
        <span class="register-tab-active" data-type="1">按楼盘推荐</span>
        <span data-type="2">按需求推荐</span>
    </div>
    <div class="register-form">
        <ul>
            <li>
                <span>客户姓名</span>
                <input type="text" id="name">
            </li>
            <li>
                <span>手机号</span>
                <input type="text" id="phone" type="number" max="19999999999" min="10000000000">
            </li>
            <li>
                <span>性别</span>
                <select id="gender">
                    <option value="男">男</option>
                    <option value="女">女</option>
                </select>
            </li>
            <li class="register-form-1">
                <span>推荐楼盘</span>
                <select id="property_id">
                    @foreach($properties as $property)
                        <option value="{{$property->id}}">{{$property->title}}</option>
                    @endforeach
                </select>
            </li>
            <li class="register-form-2">
                <span>置业区域</span>
                <input type="text" id="intention_area">
            </li>
            <li class="register-form-2">
                <span>物业类型</span>
                <select id="intention_type">
                    @foreach($propertyTypes as $type)
                        <option value="{{$type}}">{{$type}}</option>
                    @endforeach
                </select>
            </li>
            <li class="register-form-2">
                <span>意向房型</span>
                <input type="text" id="intention_apartment">
            </li>
            <li class="register-form-2">
                <span>意向总价</span>
                <input type="text" id="intention_price">
            </li>
            <li>
                <span>备注</span>
                <input type="text" id="remark">
            </li>
            <li class="sub">
                <p id="btn">推荐</p>
            </li>
        </ul>
    </div>
</section>

<script src="/static/js/jquery-2.1.3.min.js"></script>
<script src="/static/js/flexible.js"></script>
<script src="/static/js/register.js"></script>
<script>
    $("#btn").click(function(){
        var para = {
            name : $('#name').val(),
            phone : $('#phone').val(),
            gender : $('#gender').val(),
            property_id : $('#property_id').val(),
            intention_price : $('#intention_price').val(),
            intention_apartment : $('#intention_apartment').val(),
            intention_type : $('#intention_type').val(),
            intention_area : $('#intention_area').val(),
            remark : $('#remark').val(),
            _token : "{{csrf_token()}}"
        }

        $.ajax({
            url:"{{route('client.store')}}",
            type: "post",
            dataType: "json",
            data: para,
            success: function (data) {
                window.location.href='{{url('myClients')}}';
            },
            error: function (data) {
                alert('电话号码,和姓名是必须,请重新填写')

            }
        });
    });
</script>
</body>
</html>

resources/views/client/edit.blade.php
@extends('layouts.admin')

@section('meta_title','编辑顾客信息')

@section('content')



    <h2 class="text-center text-success"> 编辑顾客信息</h2>

    {!! Form::model($client, ['route' => ['client.update',$client], 'method' => 'put']) !!}
    {!! Form::text('id', $client->id, ['class' => 'form-control hidden']) !!}
    {!! Form::label('name', '姓名', ['class' => 'control-label']) !!}
    {!! Form::text('name',null, ['class' => 'form-control']) !!}

    {!! Form::label('phone', '手机号码', ['class' => 'control-label']) !!}
    {!! Form::text('phone',null, ['class' => 'form-control']) !!}

    {!! Form::label('gender', '性别', ['class' => 'control-label']) !!}
    {!! Form::select('gender', ['男'=>'男','女'=>'女'] , null , ['class' => 'form-control']) !!}

    {!! Form::label('intentions_price', '意向价格', ['class' => 'control-label']) !!}
    {!! Form::text('intention_price',null, ['class' => 'form-control']) !!}


    {!! Form::label('intention_area', '意向区域', ['class' => 'control-label']) !!}
    {!! Form::text('intention_area',null, ['class' => 'form-control']) !!}


    {!! Form::label('intention_type', '意向户型', ['class' => 'control-label']) !!}
    {!! Form::text('intention_type',null, ['class' => 'form-control']) !!}


    {!! Form::label('intention_apartment', '意向住宅', ['class' => 'control-label']) !!}
    {!! Form::text('intention_apartment',null, ['class' => 'form-control']) !!}


    {!! Form::label('remark', '备注', ['class' => 'control-label']) !!}
    {!! Form::text('remark',null, ['class' => 'form-control']) !!}
    @if($client->is_finished)
        <label>
            {!! Form::checkbox('is_finished','0', true ) !!}
            <span class="text-success">客户是否成交</span>
        </label>
    @else
        <label>
            {!! Form::checkbox('is_finished','1', false ) !!}
            <span class="text-success">客户是否成交(成交打钩,未成交不打勾)</span>
        </label>
    @endif








    {!! Form::submit('Submit', ['class' => 'form-control btn-success']) !!}
    {!! Form::close() !!}


@endsection

@section('script')
    <script>
        $('#client').addClass("active");
    </script>
@endsection

resources/views/client/index.blade.php
@extends('layouts.admin')


@section('meta_title','顾客列表')


@section('content')
    <div class="well-lg">
        <h2 class="text-center text-success">顾客列表</h2>
        <table class="table table-striped table-hover table-responsive table-condensed table-bordered">
            <thead>
            <tr>
                <th>ID</th>
                <th>职业姓名</th>
                <th>顾客名字</th>
                <th>手机</th>
                <th>性别</th>
                <th>意向价格</th>
                <th>意向价格</th>
                <th>意向区域</th>
                <th>意向房型</th>
                <th>意向楼盘</th>
                <th>备注说明</th>
                <th>操作</th>
            </tr>
            </thead>
            <tbody>
            @foreach($clients as $client)
                <tr>
                    <td>{{$client->id}}</td>
                    <td>{{$client->user->name}}</td>
                    <td>{{$client->name}}</td>
                    <td>{{$client->phone}}</td>
                    <td>{{$client->gender}}</td>
                    <td>{{$client->intention_price}}</td>
                    <td>{{$client->intention_area}}</td>
                    <td>{{$client->intention_type}}</td>
                    <td>{{$client->intention_apartment}}</td>
                    <td>{{$client->recommend_property}}</td>
                    <td>{{$client->remark}}</td>
                    <td>
                        @if($client->progresses->count())
                            <a class="btn btn-success" href="{{route('client.show',$client)}}">进度</a>

                        @endif
                        <a class="btn btn-info" href="{{route('client.edit',$client)}}">编辑</a>
                        {!! Form::model($client, ['route' => ['client.destroy', $client], 'method' => 'delete']) !!}
                        {!! Form::submit('删除', ['class' => 'form-control btn-danger btn-xs']) !!}
                        {!! Form::close() !!}

                    </td>
                </tr>
            @endforeach

            </tbody>


        </table>

    </div>
@endsection


@section('script')
    <script>
        $(function(){

            $('#client').addClass("active");
        });
    </script>
@endsection

resources/views/client/myClients.blade.php
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="format-detection" content="telephone=no"/>
    <meta name="format-detection" content="email=no"/>
    <meta name="apple-mobile-web-app-capable" content="yes"/>
    <meta name="apple-mobile-web-app-status-bar-style" content="black"/>
    <title>全民经纪人</title>

    <link rel="stylesheet" href="/static/css/index.css"/>
</head>
<body>
<section class="custom">
    <div class="custom-top">
        <p>
            <em><img src="/static/img/custom-pic.png" alt=""></em>
            <span>我的客户</span>
        </p>

        <div class="custom-right">
            <p>{{$clients->count()+$dealers->count()}}</p>
            <p>推荐中总数</p>
        </div>
    </div>
    <div class="custom-tab">
        <span class="custom-tab-active"><a href="javascript:;">推荐中（{{$clients->count()}}）</a></span>
        <!-- <span><a href="javascript:;">购房进度（2）</a></span> -->
        <span class="tab-token"><a href="javascript:;">已成交（{{$dealers->count()}}）</a></span>
    </div>
    <div class="custom-search">
        <p>
            <em><img src="static/img/search.png" alt=""></em>
            <input type="text">
        </p>
    </div>
    {{--推荐中 客户--}}

    <div class="custom-con" id="customIng">
        <ul>
            @foreach($clients as $client)
                <li>
                    <div class="custom-con-l">
                        <p>{{$client->name}}</p>
                    </div>
                    <div class="custom-con-c">
                        <div class="custom-con-t">{{$client->phone}}&nbsp;&nbsp;推荐中</div>
                        <p>推荐楼盘：{{$client->recommend_property}}</p>

                        <p>接收置业顾问:{{$client->user->name}}</p>
                    </div>
                    <div class="custom-con-r">
                        <a href="tel:{{$client->phone}}">
                            <img src="/static/img/phone.png" alt=""  width="50" height="50">
                        </a>
                        @if($client->progresses->count())
                            <a href="{{route('client.show',$client)}}">
                                购房进度
                            </a>
                        @endif
                    </div>
                </li>

            @endforeach

        </ul>
    </div>

    {{--已成交 客户--}}
    <div class="custom-con" id="customDone">
        <ul>
            @foreach($dealers as $client)
                <li>
                    <div class="custom-con-l">
                        <p>{{$client->name}}</p>
                    </div>
                    <div class="custom-con-c">
                        <div class="custom-con-t">{{$client->phone}}&nbsp;&nbsp;推荐中</div>
                        <p>推荐楼盘：{{$client->recommend_property}}</p>

                        <p>接收置业顾问:{{$client->user->name}}</p>
                    </div>
                    <div class="custom-con-r">
                        <a href="tel:{{$client->phone}}">
                            <img src="/static/img/phone.png" alt="" width="50" height="50">
                        </a>
                        @if($client->progresses->count())
                            <a href="{{route('client.show',$client)}}">
                                购房进度
                            </a>
                        @endif
                    </div>
                </li>

            @endforeach

        </ul>
    </div>
    <div class="custom-btn">
        <p class="sub"><a href="javascript:history.go(-1);">返回首页</a></p>
    </div>
</section>

<script src="/static/js/jquery-2.1.3.min.js"></script>
<script src="/static/js/flexible.js"></script>
<script>
$(function(){
    $('#customDone').hide();
    $('.custom-tab span').click(function(){
        $('.custom-tab span').removeClass('custom-tab-active');
        $(this).addClass('custom-tab-active');
        if($(this).hasClass('tab-token')){
            $('#customIng').hide();
            $('#customDone').show();
        }else{
            $('#customDone').hide();
            $('#customIng').show();
        }
    })
})
</script>
</body>
</html>

resources/views/client/show.blade.php
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="format-detection" content="telephone=no" />
    <meta name="format-detection" content="email=no" />
    <meta name="apple-mobile-web-app-capable" content="yes" />
    <meta name="apple-mobile-web-app-status-bar-style" content="black" />
    <title>全民经纪人</title>

    <link rel="stylesheet" href="/static/css/index.css" />
</head>
<body>
<section class="setbacks">
    <div class="setbacks-top">
        <p>
            <span>购房进度</span>
        </p>
    </div>
    <div class="setbacks-ul">
        <p class="setbacks-ul-title">{{$client->recommend_property}}</p>

        @if(empty($client->progresses))
            <p>暂时没有顾客进度信息!</p>
        @else
            <ul>
                @foreach( $client->progresses as $progress)
                <li>
                    <p>{{$progress->stage}}</p>
                    <p>{{$progress->stage_time}}</p>
                </li>
                @endforeach

            </ul>
        @endif



    </div>
</section>

<script src="/static/js/jquery-2.1.3.min.js"></script>
<script src="/static/js/flexible.js"></script>
</body>
</html>